// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypdxiuhqwskpmwbbhedb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZHhpdWhxd3NrcG13YmJoZWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTM4MDYsImV4cCI6MjA1NTg2OTgwNn0.6JudhK_TKa29bGtL2GHtkveendkiDJj86okCIqd2_ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);